services:
  flux:
    container_name: flux_app
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/flux
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=password123
      - MINIO_BUCKET=flux-artifacts
      - POLLING_INTERVAL=2000
      - MAX_QUEUE_SIZE=100
    depends_on:
      - mongo
      - redis
      - minio
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/scheduler-jobs:/tmp/scheduler-jobs
 
  mongo:
    image: mongo:latest
    container_name: flux_test_mongo
  
  redis:
    image: redis:alpine
    container_name: flux_test_redis

  minio:
    image: minio/minio
    container_name: flux_test_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "password123"